[package]
name = "tetrust"
version = "0.1.0"
authors = ["Scott Munro <scottnmunro@gmail.com>"]
edition = "2018"

[dependencies]
pancurses = "0.16"
savefile = "0.7.4"
savefile-derive = "0.7.4"
snm_rand_utils = { git = "https://github.com/scottnm/snm_rand_utils", branch = "main" }
